### ISSUE TITLE
wrong version of vue-template-compiler

### ISSUE THREAD

**Issue by phwecker** [microsoft/rating-web#9]
upon deployment (locally or as part of the OpenShift lab), deplolyment raises error around version of vue(-template-compiler). 

```
ERROR in ./src/App.vue
Module build failed: Error: 

Vue packages version mismatch:

- vue@2.6.11 (/rating-web/node_modules/vue/dist/vue.runtime.common.js)
- vue-template-compiler@2.6.10 (rating-web/node_modules/vue-template-compiler/package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

    at Object.<anonymous> (/rating-web/node_modules/vue-template-compiler/index.js:10:9)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/rating-web/node_modules/vue-loader/lib/parser.js:1:80)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
 @ ./src/main.js 2:0-24
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 ./src/main.js

ERROR in ./src/components/Home.vue
Module build failed: Error: 

Vue packages version mismatch:

- vue@2.6.11 (/rating-web/node_modules/vue/dist/vue.runtime.common.js)
- vue-template-compiler@2.6.10 (/rating-web/node_modules/vue-template-compiler/package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

    at Object.<anonymous> (/rating-web/node_modules/vue-template-compiler/index.js:10:9)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/rating-web/node_modules/vue-loader/lib/parser.js:1:80)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
 @ ./src/router/index.js 3:0-38
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 ./src/main.js

ERROR in ./src/components/Rating.vue
Module build failed: Error: 

Vue packages version mismatch:

- vue@2.6.11 (/rating-web/node_modules/vue/dist/vue.runtime.common.js)
- vue-template-compiler@2.6.10 (/rating-web/node_modules/vue-template-compiler/package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

    at Object.<anonymous> (/rating-web/node_modules/vue-template-compiler/index.js:10:9)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/rating-web/node_modules/vue-loader/lib/parser.js:1:80)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
 @ ./src/router/index.js 4:0-42
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 ./src/main.js

ERROR in ./src/components/Leaderboard.vue
Module build failed: Error: 

Vue packages version mismatch:

- vue@2.6.11 (/rating-web/node_modules/vue/dist/vue.runtime.common.js)
- vue-template-compiler@2.6.10 (/rating-web/node_modules/vue-template-compiler/package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

    at Object.<anonymous> (/rating-web/node_modules/vue-template-compiler/index.js:10:9)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/rating-web/node_modules/vue-loader/lib/parser.js:1:80)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
 @ ./src/router/index.js 5:0-52
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 ./src/main.js

ERROR in ./src/components/Footer.vue
Module build failed: Error: 

Vue packages version mismatch:

- vue@2.6.11 (/rating-web/node_modules/vue/dist/vue.runtime.common.js)
- vue-template-compiler@2.6.10 (/rating-web/node_modules/vue-template-compiler/package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

    at Object.<anonymous> (/rating-web/node_modules/vue-template-compiler/index.js:10:9)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/rating-web/node_modules/vue-loader/lib/parser.js:1:80)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
 @ ./src/router/index.js 6:0-42
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 ./src/main.js
```
installing a later version of the rogue dependencies solved the compiler issue and allowed successful deployment.

**Comment by sabbour** [comment]
Fixed in https://github.com/microsoft/rating-web/pull/11
